sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shiva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shiva/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  edge: true
  app: 'shiva_docker'
  env: 'shivadocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-183826604270'
  bucket_path: 'shiva_docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
